name: lint
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
permissions:
  contents: read
env:
  UV_FROZEN: "true"
  WORKDIR: ${{ inputs.working-directory == '' && '.' || inputs.working-directory }}
  RUFF_OUTPUT_FORMAT: github
jobs:
  build:
    name: "make lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + uv
        uses: "./.github/actions/uv_setup"
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with lint --with dev
      - name: Analysing the code with our lint
        run: |
          make lint_package
      - name: Install test dependencies
        run: |
          poetry install --with test
      - name: Analysing the tests with our lint
        run: |
          make lint_tests